#This plugin is dedicated to Kira
flags:
  errors:
    Interact: "No puedes interactuar aqui"
    Build: "No puedes construir aqui"
    Break: "No puedes romper aqui"
    Damage: "No puedes hacer hacer daño aqui"
    Use_bed: "No puedes dormir aqui"
    Bucket: "No puedes usar este item aqui"
    Player_Ignite: "No puedes prender fuergo aqui"
villa_specification:
  #set to false deactivates only regions with flag "is_village_zone: true"
  protection: true
  size_villa: 250
  size_name: 16
  max_villa_per_player: 3
  overlapping_villa: false
  title_to_enter: "&aHas entrado a"
  title_to_exit: "&cHas salido de"
  specification_by_perm:
    #the priority has the last
    villa_vip:
      permission: "villaregion.feature.vip"
      size_villa: 300
      size_name: 17
      max_villa_per_player: 3
    #villa_mega_vip has priority because is the last
    villa_mega_vip:
      permission: "villaregion.feature.megavip"
      size_villa: 450
      size_name: 18
      max_villa_per_player: 5
  default_flags_villa:
    Not_Burn: true
    Not_Explosion: true
    Not_Natural_Ignite: true
    Title: true
commands:
  villa:
    create:
      name: "crear"
      description: "El comando para crear villa"
      error:
        name_usage: "El %name_usage% ya esta en uso"
        size_name: "El nombre como maximo puede ser de %size_name%"
        max_villa_per_player: "El maximo de villa es de %max_villa_per_player%, tu tienes %count_villa_player%"
        overlapping_villa: "La zona esta colisionando con %overlapping_villa%"
      success:
        create_region: "La zona %create_region% se ha creado"
    delete:
      name: "borrar"
      description: "El comando para borrar villas"
      error:
        not_found: "No tienes una villa de nombre %name_villa%"
      success:
        deleted: "La villa %name_villa% ha sido borrada"
    config:
      name: "configuracion"
      description: "El comando para configurar la villa"
      subcommands:
        permission: "permisos"
        spawn: "spawn"
        name: "nombre"
      error:
        not_found_villa: "La villa no existe"
        player_is_not_resident: "No eres parte de la villa"
        player_doesnt_have_permission: "No tienes permisos para esa accion"
        invalid_permission_name: "El permiso no existe"
        option_not_valid: "Ingrese false, true o remove"
        max_villa_per_player: "El jugador ya tiene demasiadas villas"
      success:
        change_spawn: "El spawn se ha cambiado"
        change_name: "El nombre de la villa ha cambiado"
        change_permission: "El permiso ha sido cambiado"
    go:
      name: "ir"
      permission: "villa.commands.teleport"
      all_can_use: true
      description: "El comando para hacer teleportacion a la villa"
      error:
        not_found_villa: "Villa no encontrada"
        player_is_not_resident: "No eres parte de esa villa"
        not_permission: "No tienes permisos para usar esto"
        villa_dont_have_spawn: "La villa no tiene un spawn"
        villa_doesnt_have_tpa_resident: "La villa no tiene esta capacidad"
      success:
        done: "La teleportacion fue un exito"
    add:
      name: "agregar"
      description: "El comando para agregar personas a las villas"
      error:
        not_found_player: "El jugador no fue encontrado"
        not_found_villa: "No tienes los permisos para agregar jugadores a la Villa"
        player_already_in_zone: "El juador ya esta en la Villa"
      success:
        added: "El jugador fue agreado"
    remove:
      name: "expulsar"
      description: "El comando para expulsar personas a las villas"
      error:
        not_found_player: "El jugador no esta en la Villa"
        not_found_villa: "No tienes los permisos para espulsar jugadores de la villa"
        not_player_in_zone: "El jugador no esta en la villa"
        can_not_remove_player_with_same_permission: "No puedes expulsar a un jugador con los mismo permisos o superiores"
      success:
        removed: "El jugador fue expulsado de la villa"
tab:
  allow_tab_commands: true
  allow_commands:
    - villa
    - tps
    - tpa