name: VillaRegion
version: '${project.version}'
main: vicente.rocka.villaregion.VillaRegion
api-version: 1.19
authors: [ Vicente_Munoz_alias_Rockimunoz74 ]
description: Village region basic
commands:
  vregion:
    description: A command for create regions
    aliases:
      - vrg
    permission: villaregion.commands.vregion
  vshop:
    description: A command for edit shop
    permission: villaregion.commands.vshop
  villa:
    description: A command for create villas
  vendo:
    description: A command for sell items
  compro:
    description: A commnad for buy items